# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
    
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="ivelin1936/VUbuntu-20-04-server"
    web.vm.box_version = "0.0.1"
    web.vm.hostname = "web.hw1.ivo"
    web.vm.provider :virtualbox do |vb|
            vb.name = "WEB_M1"
        end
    web.vm.network "private_network", ip: "192.168.56.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.synced_folder ".", "/vagrant"
    web.vm.provision "shell", inline: <<EOS
    
echo "## Add hosts ..."
echo "192.168.56.100 web.hw1.ivo web" >> /etc/hosts
echo "192.168.56.101 db.hw1.ivo db" >> /etc/hosts

echo "## Solving dpkg-reconfigure: unable to re-open stdin: No file or directory..."
sudo rm -v /etc/apt/apt.conf.d/70debconf

echo "## Install Software (httpd, php libapache2-mod-php php-mysql and git)..."
sudo apt-get update
sudo apt-get -s upgrade | grep -P "\d\K upgraded"

sudo apt-get -y install apache2
apache2 -version
sudo service apache2 start
sudo service apache2 status

echo "## Checking the Web Server..."
sudo systemctl is-active apache2
sudo systemctl is-enabled apache2
sudo systemctl status apache2

echo "## Opening Apache Ports in UFW Firewall (HTTP 80/tcp, HTTPS 443/tcp)..."
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
sudo ufw status

sudo apt-get install -y php libapache2-mod-php php-mysql

echo "## Installing git..."
sudo apt-get -y install git

echo "## Clone application repository..."
msg=$(sudo git clone https://github.com/shekeriev/dob-module-1.git 2>&1)
echo $msgvm.synced_folder

cp dob-module-1/web/* /var/www/html
sudo rm -rf dob-module-1
cd /var/www/html
sudo rm config.php || true
echo "## Load DB Configurations..."
cp /vagrant/config.php /var/www/html

echo "## Rename default Apache's '/var/www/html/index.html' to prevent it's load instead of our index.php..."
sudo mv /var/www/html/index.html /var/www/html/apache2_index.html

#sudo apt-get -y install policycoreutils selinux-utils selinux-basics
#sudo selinux-activate
#sudo selinux-config-enforcing
#sudo setsebool -P httpd_can_network_connect=1

EOS
  end

  config.vm.define "db" do |db|
    db.vm.box="ivelin1936/VUbuntu-20-04-server"
    db.vm.box_version = "0.0.1"
    db.vm.hostname = "db.hw1.ivo"
    db.vm.provider :virtualbox do |vb|
            vb.name = "DB_M1"
        end
    db.vm.network "private_network", ip: "192.168.56.101"
    db.vm.provision "shell", inline: <<EOS
echo "## Add hosts ..."
echo "192.168.56.100 web.hw1.ivo web" >> /etc/hosts
echo "192.168.56.101 db.hw1.ivo db" >> /etc/hosts

echo "Solving dpkg-reconfigure: unable to re-open stdin: No file or directory..."
sudo rm -v /etc/apt/apt.conf.d/70debconf

echo "## Install Software (mariadb mariadb-server)..."
sudo apt-get update
sudo apt-get -y install mariadb-server

sudo systemctl stop mariadb
echo "## Starting MatiaDB ..."
sudo systemctl enable mariadb
sudo systemctl start mariadb
sudo systemctl status mariadb

echo "## Open firewall appropriate port (3306) only for the WEB machine..."
sudo ufw allow from 192.168.56.100 to any port 3306
#sudo ufw allow 3306/tcp
sudo ufw enable
sudo ufw status

#echo "## Stoping firewall..."
#sudo ufw disable

echo "## Installing git..."
sudo apt-get -y install git

echo "## Clone application repository..."
msg=$(sudo git clone https://github.com/shekeriev/dob-module-1.git 2>&1)
echo $msg

echo "## Create and load the database ..."
cd dob-module-1/db/
sudo mysql -u root < db_setup.sql
cd ../..
sudo rm -rf dob-module-1

echo "Configurating MariaDB Remote Access..."
sudo sed -i 's/bind-address/#bind-address/g' /etc/mysql/mariadb.conf.d/50-server.cnf
echo "Restarting MariaDB service..."
sudo systemctl restart mariadb.service

echo "## Installing net tools and check 3306 port..."
sudo apt-get update
sudo apt-get -y install net-tools
sudo netstat -anp | grep 3306

EOS
  end

end
