# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |docker|
  docker.vm.box = "ivelin1936/VCentos"
  docker.vm.box_version = "0.0.1"
  docker.vm.hostname = "docker.hw1.ivo"
  docker.vm.network "private_network", ip: "192.168.95.100"
  docker.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  docker.vm.provision "shell", path: "docker-setup.sh"
  docker.vm.synced_folder "./resources", "/resources"
  docker.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.name = "CentosOS_HOST"
  end
end
