# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box="ivelin1936/VCentos"
    jenkins.vm.hostname = "jenkins.do1.lab"
    jenkins.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
      vb.name = "JENKINS_HOST"
    end
    jenkins.vm.network "private_network", ip: "192.168.56.11"
    jenkins.vm.network "forwarded_port", guest: 80, host: 8000
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.provision "shell", path: "host_config.sh"
    jenkins.vm.provision "shell", path: "docker-setup.sh"
    jenkins.vm.provision "shell", path: "jenkins-setup.sh"
    #jenkins.vm.provision "shell", path: "additional_jenkins_settings.sh"
  end
  
end
